app:
  cors:
    allowed-origins: ${CORS_ORIGIN:}
  super-admin:
    email: admin@wealthview.local
    password: ${SUPER_ADMIN_PASSWORD}

logging:
  level:
    com.wealthview: INFO
    org.springframework: WARN
