package com.wealthview.persistence.entity;

import java.util.UUID;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * Base for mutable entities keyed by a random UUID primary key, generated by Hibernate
 * on insert (see {@link Auditable} for the {@code created_at} / {@code updated_at} stamps).
 *
 * <p>Extracted from ~24 entities that each declared the identical
 * {@code @Id @GeneratedValue(strategy = GenerationType.UUID) private UUID id;} field plus
 * {@code getId()} getter. {@code MobileAppVersionEntity} extends {@link Auditable} directly
 * (not this class) because its primary key is the {@code platform} string, not a
 * generated UUID.
 */
@MappedSuperclass
public abstract class UuidAuditable extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    public UUID getId() {
        return id;
    }
}
