package com.wealthview.persistence.entity;

import java.util.UUID;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;

/**
 * Base for append-only entities keyed by a random UUID primary key, generated by
 * Hibernate on insert (see {@link CreatedAtEntity} for the {@code created_at} stamp).
 *
 * <p>Extracted from ~24 entities that each declared the identical
 * {@code @Id @GeneratedValue(strategy = GenerationType.UUID) private UUID id;} field plus
 * {@code getId()} getter. Entities with a non-UUID or composite primary key (e.g.
 * {@code PriceEntity}, {@code SystemConfigEntity}) must NOT extend this class.
 */
@MappedSuperclass
public abstract class UuidCreatedAtEntity extends CreatedAtEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    public UUID getId() {
        return id;
    }
}
